### ISSUE TITLE
App crashes when using inceptionv3 models

### ISSUE THREAD

**Issue by farazk86** [dpinthinker/AStyleTransfer#2]
Hi,

Thank you for writing this code, it greatly helped me understand image processing in java. I am trying to use a models based on inceptionv3 to get better quality results, and downloaded the models from [tfhub](https://tfhub.dev/sayakpaul/lite-model/arbitrary-image-stylization-inceptionv3/fp16/transfer/1).

But the problem is when using these models, your app crashes with the error: 

```
A/libc: /usr/local/google/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type std::bad_alloc: std::bad_alloc" failed
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 32555 (.astyletransfer), pid 32555 (.astyletransfer)
```

the models have the same input/output shapes and should work exactly the same as the other models, then why do they crash the app?

Thanks

**Comment by farazk86** [comment]
It turned out that I was getting this error because I forgot that I had edited the code a bit and unknowingly created a memory leak.

**Comment by dpinthinker** [comment]
> It turned out that I was getting this error because I forgot that I had edited the code a bit and unknowingly created a memory leak.

Great！
